# GitHub API configuration
github:
  token: "your_github_token_here"
  base_url: "https://api.github.com"
  rate_limit:
    enabled: true
    max_requests_per_hour: 5000

# Logging configuration
logging:
  log_file: "logs/crawler.log"
  log_level: "INFO"

# File handling configuration
files:
  download_directory: "data/downloaded_files"
  supported_extensions:
    - ".md"
    - ".json"
    - ".pdf"
    - ".mediawiki"

# Repositories configuration
repositories:
  to_skip:
    - "repo1"
    - "repo2"
  only_include:
    - "nikku::didi"
  get_extended_fork_info: true
  get_user_data: true
  get_org_data: true
  max_fork_depth: 1

# Metadata configuration
metadata:
  file_name: "metadata.json"
  timestamp_format: "%m-%d-%Y %H:%M:%S"

# Users and organizations to crawl
crawl_targets:
  - "nikku"
  # - "dane-git"
  #- "github"
